version: 2

jobs:
  # This job needs a token to push to origin 
  sync-staging-with-master:
    docker:
    - image: circleci/node:12.14.1-browsers
    steps:
      - checkout
      - run:
          name: Sync branches (master -> staging)
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              if git show-ref --verify --quiet "refs/heads/staging"; then
                git branch -D staging 
              fi
              git checkout -b staging
              git remote set-url origin ${CIRCLE_REPOSITORY_URL/git/$GITHUB_TOKEN}
              git push origin staging
            fi
workflows:
  version: 2
  sample: 
    jobs:
      - sync-staging-with-master
